### ISSUE TITLE
XDR Read Error: Unknown OperationType member for value 24

### ISSUE THREAD

**Issue by rust-master** [stellar/js-soroban-client#122]
I'm using the Typescript client and facing an issue on React side when invoking the write function of the contract.

Error:
```
Error: XDR Read Error: Unknown OperationType member for value 24
    at h (contentScript.min.js:1:13535)
(anonymous) @ contentScript.min.js:1
```

Code:
```
import * as SorobanClient from "soroban-client";
import * as exampleProject from "ExampleProject";
 let data = await exampleProject.setName(
       {
         value:  "John",
       }
     );
```

**Comment by Shaptic** [comment]
This can be caused by having both `soroban-client` and `stellar-sdk` installed for the same project. The former will bring in the latest, futurenet-compatible XDR as part of the stellar-base dependency, while the latter will bring in the current, pubnet-compatible XDR as part of that dependency. You should prefer the latter or ensure only one stellar-base package version is installed.
