### ISSUE TITLE
`prepareTransaction` requires networkPassphrase on Futurenet

### ISSUE THREAD

**Issue by piyalbasu** [stellar/js-soroban-client#54]
**Describe the bug**
On Futurenet, when calling `server.prepareTransaction`, the second param of `networkPassphrase` is optional, but we've observed that it is required: https://github.com/stellar/js-soroban-client/blob/main/src/server.ts#L406

Callng `server.prepareTransaction` without the second param of `networkPassphrase` results in an error: `{code: -32602, message: 'invalid parameters: [-32602] invalid parameters'}`

Adding the `networkPassphrase` param appears to fix the issue.

This example also describes the second param as optional: https://github.com/stellar/js-soroban-client/blob/main/docs/reference/examples.md

**What version are you on?**
v0.4.0

**To Reproduce**
On Futurenet (https://horizon-futurenet.stellar.org/) and using the RPC Server URL `https://stellar-futurenet.4d63.com/soroban/rpc:

Try to build a tx similar to the example above. Observe that calling `server.prepareTransaction` with only the required param results in an error

**Expected behavior**
 `server.prepareTransaction` should only require the transaction as a param

**Comment by aristidesstaffieri** [comment]
This is actually only an issue on Futurenet, it seems that `getNetwork` is not supported for Futurenet in Horizon yet which is the fallback to not passing a passphrase explicitly in `prepareTransaction`.

```{
  code: -32602,
  message: 'invalid parameters: [-32602] invalid parameters'
}```

**Comment by aristidesstaffieri** [comment]
So this actually does work on Futurenet also, our problem in Freighter is that we're using the Soroban RPC interchangeably with the Horizon endpoints for this. Since the API for sending a tx is the same, we're able to build and prepare a tx aimed at the Soroban RPC when we explicitly pass in the passphrase because when you do that, the sdk skips the call to `getNetwork` which is not part of the Soroban RPC interface, only the Horizon interface.

We might be confused about when we should be using the Futurenet Horizon instance vs the Soroban RPC but[ the docs](https://github.com/stellar/js-soroban-client/blob/main/docs/reference/examples.md) do show an example of instantiating the `SorobanClient.Server` with an rpc endpoint and then preparing a transaction without passing in the passphrase which would fail right now.

**Comment by aristidesstaffieri** [comment]
> 

Actually I see that `getNetwork` is supported, so maybe this is a config bug in the deployment of `https://rpc-futurenet.stellar.org`. You can use this script to repro the behavior -

```
const SorobanClient = require('soroban-client');

const WORKS = "https://horizon-testnet.stellar.org"
const ALSO_WORKS = 'https://horizon-futurenet.stellar.org'
const DOESNT_WORK = "https://rpc-futurenet.stellar.org"

const server = new SorobanClient.Server(
  DOESNT_WORK
);

(async function main() {
  try {
    const network = await server.getNetwork() // or getHealth
  } catch (error) {
    console.log('error')
    console.log(error)
  }
})();
```

It seems that `getHealth` also doesn't work on this rpc instance.

**Comment by Shaptic** [comment]
I know this is an old bug bug I can't reproduce it, so I think the RPC server has been fixed:

Given your repro script:

```ts
const SorobanClient = require('soroban-client');
const DOESNT_WORK = "https://rpc-futurenet.stellar.org";
(async function main() {
    const server = new SorobanClient.Server(DOESNT_WORK);

    try {
        const network = await server.getNetwork() // or getHealth
        console.log(network)
    } catch (error) {
        console.log('error')
        console.log(error)
    }
})();
```

I get the following output (after `npm init -y && npm i soroban-client@0.8.1`):

```
$ node index.js
{
  friendbotUrl: 'https://friendbot-futurenet.stellar.org/',
  passphrase: 'Test SDF Future Network ; October 2022',
  protocolVersion: '20'
}
```
